#!/bin/bash
psql -U "$POSTGRES_USER" -d "$POSTGRES_DB" <<-EOSQL
    CREATE USER "$APP_USER" WITH PASSWORD '$APP_PASSWORD';
    GRANT CONNECT ON DATABASE "$POSTGRES_DB" TO "$APP_USER";
    GRANT USAGE ON SCHEMA public TO "$APP_USER";
    ALTER DEFAULT PRIVILEGES IN SCHEMA public
      GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO "$APP_USER";
EOSQL
