# Production secrets — fill in values before deploying
apiVersion: v1
kind: Secret
metadata:
    name: beanstash-secret
type: Opaque
stringData:
    SPRING_DATASOURCE_URL: ENC[AES256_GCM,data:61xtitzF4J1aDMGtzN7Ikbng+SVj4qpeLcwUmYmCM8vhOiAtnRJgd+z24cB/fL7CKFOr,iv:gMXEd3yTFpV7XMDYIo2ZSEfxrZQMqPeCnEGDlLZX9GI=,tag:1xYvpHEyQdM31CfsYWFjtg==,type:str]
    SPRING_DATASOURCE_USERNAME: ENC[AES256_GCM,data:p6FP+X+/q3kSoQHmUQ==,iv:n8deUOs7Ne3e1wrb86yVNTYaGxaeUteoZuLAopAIl88=,tag:ul/6Bbb7hTkLaKfaD3EWQA==,type:str]
    SPRING_DATASOURCE_PASSWORD: ENC[AES256_GCM,data:WFvvHJWlLfnRIdx24Wou1NbJg9fNolQkQSnGY0K+,iv:jhMsrW5YnyLTfISJN5KfkCVOf4QCcHWlkzPRvtiag/8=,tag:8bNDw2EDvozNNTW3MVrtUA==,type:str]
    SPRING_FLYWAY_USER: ENC[AES256_GCM,data:xiPFjxyIA91w,iv:mTGORzRYSnFc/lSaZrc/q7dbBSPevypb746T3UrF5Ds=,tag:OV05/2c2N7Ir7Fn2Q3WaMQ==,type:str]
    SPRING_FLYWAY_PASSWORD: ENC[AES256_GCM,data:vFALg4w9lRFlVt+al5K/5c1YSkKeUtfeKtTfZWHO,iv:WlcYElxhRww5Piw9qyEulRP7uqbpXPSDP6cGU/s+W8M=,tag:zk1KVDkmYFrZbXmO0PFQAg==,type:str]
    SENTRY_DSN: ENC[AES256_GCM,data:PaWAM7LVwjvgLc5cSpNxc4ci+1bpooPENCAtvsqLfBg1ZMzfu6Sf3+btn8OjN6T5nY4eYrsgjJ5lVs44Gg==,iv:WhjMOOiUi+w7XOMG9MHEeBIJBJVe6DxfuaMAktlJcHk=,tag:NU9HvPIt5bbu9xospmKrZg==,type:str]
    NEXT_PUBLIC_SENTRY_DSN: ENC[AES256_GCM,data:gw5lbg1TGkvfPKQOIHHaJLMXn3j1jCN3dRWnrtTDAe5o1j6eRNSARiSWeUuKQL3fJ0T/2IO3Zt/pGz4tUA==,iv:kzrKeoRCV+t6k2h94ZObg9balIQAp7ZZW7B57fprYvU=,tag:3qwov/J0EFnI8l4674ry1A==,type:str]
sops:
    lastmodified: "2026-03-14T16:06:33Z"
    mac: ENC[AES256_GCM,data:rc8TLoX1feY8NvtAIclGYlwoJtvHOZSROje1RVA91dy8XFn0ev1iNsDHHc+vJ6XIXZj8Jn08x3BN9x1DOtFF7HAAGD4EPUqOIQ7dM0LVBT3ExjyLz6aDyD4CPiOMrIA9lccxSLUB4TQVttdQXorIZUFQk9U4T0JZfwNbzX/cmek=,iv:WYVnuhdeCPm6EdYzgMupIQX0noSdkxYy9mCNWrnh6rY=,tag:wDX+v9+r2NP0eXzVwb0HuA==,type:str]
    pgp:
        - created_at: "2026-03-14T16:06:33Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA/cF29oNCPyWAQ/8DBIWMXfl3Uc+E2K9pXEtuFki8Os5VD41wVG73yPTxlqP
            fJuGXt2mhm3lehYhzYTrJUnCh1QF8mdVAuLpED3MoQephg+hnjAId4m5lTAiI0Nj
            BbdEVy4eij0OuxkBzJfImHLhblIO5QjtMFfi94S1cJQIwGYhcsU5kEmluxy4qFaf
            dfpokmgGdS8stMu50aZAOD4nE5mudVd2EPTef6dcQWJwSB5BVYAQ7oA4dgcolZT3
            eYQCui9cD0xUgqTKr9rMB0+6CKE8mJy6JuFnaJV0yiSkUN8VZhyGSmIS7lss4RzD
            Pd5wg/fVsafo06btH2oUrx6Z+EODsjX+xcEZ/O62unYKFBVhVbLjPXIymKYnHCqO
            2Ygy1rcVmuAl1HvK0dGi7RgkE9nJOGkXlcgRdnMz4prTa+rCMA6F5kmDGxZA8SJZ
            zOTTcGmyPyrhdmqPzatod2Dr9tt/I2bSW4LHROFKOXoWOql5tjiIUDIEFxlmzR6W
            C+2fGaqRfyQS7lDTyrAcwmdH68pgpet6pDwXy0I5i1LOZww8yCPc0l6NT+6fIY08
            V1IGhXg16GAdhCs4SfFR9EGFvvHW8nIjmIxDG9qi71XdZvT5B1irSgTTUdnVftm2
            lX2dJrzGaWnZpMs2HpE6tvk87+I2oKSUilIVqoFrGT8lHHB+T/k9+S9znulPZZnU
            ZgEJAhBJfZ3wv6KG/BMvOBqSZQvuD/TxU1+GKpM/8elyJ54+zZYllr46UQS9zLXy
            rDCTIy92gOrkrrxEpHHVEOH70p+wUqgJApkWdANtID99MAedBG1M1JVl1lSdqWJu
            FC6VZo+pmg==
            =QPRA
            -----END PGP MESSAGE-----
          fp: 05F6A512DD349B0E33C7F417CBB5F307693F111D
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
---
apiVersion: v1
kind: Secret
metadata:
    name: beanstash-postgres-secret
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:9a0ER6ZIJZAe,iv:KXLVfHkR4Ew0K2xj6xu54cBwiuLRfqE89qCTt5gKVhA=,tag:r+2jjlezSYfcSR7ohEaFIg==,type:str]
    password: ENC[AES256_GCM,data:lWOcXH80aKDJ6/Wg/woVRd9UQ3CM6tCC5yhlCvdr,iv:ljH8whR5CYbG46lV3zymkoeIEz3yo/PTTQDkIPbDqqE=,tag:jPSwi0tWxz3oLiuSxfoc7w==,type:str]
sops:
    lastmodified: "2026-03-14T16:06:33Z"
    mac: ENC[AES256_GCM,data:rc8TLoX1feY8NvtAIclGYlwoJtvHOZSROje1RVA91dy8XFn0ev1iNsDHHc+vJ6XIXZj8Jn08x3BN9x1DOtFF7HAAGD4EPUqOIQ7dM0LVBT3ExjyLz6aDyD4CPiOMrIA9lccxSLUB4TQVttdQXorIZUFQk9U4T0JZfwNbzX/cmek=,iv:WYVnuhdeCPm6EdYzgMupIQX0noSdkxYy9mCNWrnh6rY=,tag:wDX+v9+r2NP0eXzVwb0HuA==,type:str]
    pgp:
        - created_at: "2026-03-14T16:06:33Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA/cF29oNCPyWAQ/8DBIWMXfl3Uc+E2K9pXEtuFki8Os5VD41wVG73yPTxlqP
            fJuGXt2mhm3lehYhzYTrJUnCh1QF8mdVAuLpED3MoQephg+hnjAId4m5lTAiI0Nj
            BbdEVy4eij0OuxkBzJfImHLhblIO5QjtMFfi94S1cJQIwGYhcsU5kEmluxy4qFaf
            dfpokmgGdS8stMu50aZAOD4nE5mudVd2EPTef6dcQWJwSB5BVYAQ7oA4dgcolZT3
            eYQCui9cD0xUgqTKr9rMB0+6CKE8mJy6JuFnaJV0yiSkUN8VZhyGSmIS7lss4RzD
            Pd5wg/fVsafo06btH2oUrx6Z+EODsjX+xcEZ/O62unYKFBVhVbLjPXIymKYnHCqO
            2Ygy1rcVmuAl1HvK0dGi7RgkE9nJOGkXlcgRdnMz4prTa+rCMA6F5kmDGxZA8SJZ
            zOTTcGmyPyrhdmqPzatod2Dr9tt/I2bSW4LHROFKOXoWOql5tjiIUDIEFxlmzR6W
            C+2fGaqRfyQS7lDTyrAcwmdH68pgpet6pDwXy0I5i1LOZww8yCPc0l6NT+6fIY08
            V1IGhXg16GAdhCs4SfFR9EGFvvHW8nIjmIxDG9qi71XdZvT5B1irSgTTUdnVftm2
            lX2dJrzGaWnZpMs2HpE6tvk87+I2oKSUilIVqoFrGT8lHHB+T/k9+S9znulPZZnU
            ZgEJAhBJfZ3wv6KG/BMvOBqSZQvuD/TxU1+GKpM/8elyJ54+zZYllr46UQS9zLXy
            rDCTIy92gOrkrrxEpHHVEOH70p+wUqgJApkWdANtID99MAedBG1M1JVl1lSdqWJu
            FC6VZo+pmg==
            =QPRA
            -----END PGP MESSAGE-----
          fp: 05F6A512DD349B0E33C7F417CBB5F307693F111D
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
