---
spring:
  application:
    name: beanstash-backend
  docker:
    compose:
      enabled: false
      file: ./backend/docker-compose.yaml
  flyway:
    placeholders:
      app_user: ${SPRING_DATASOURCE_USERNAME}
      app_password: ${SPRING_DATASOURCE_PASSWORD}
app:
  url: http://localhost:8080
  rp-id: localhost
