spring.application.name=beanstash-backend
spring.docker.compose.enabled=false
spring.docker.compose.file=./backend/docker-compose.yaml
spring.flyway.placeholders.app_user=${SPRING_DATASOURCE_USERNAME}
spring.flyway.placeholders.app_password=${SPRING_DATASOURCE_PASSWORD}
