apiVersion: v1
kind: ConfigMap
metadata:
  name: beanstash-config
  labels:
    app.kubernetes.io/name: beanstash
    app.kubernetes.io/component: application
data:
  SPRING_PROFILES_ACTIVE: prod
  TZ: Europe/Amsterdam
  POSTGRES_HOST: beanstash-postgres
  NEXT_PUBLIC_API_URL: https://api.beanstash.org
  SENTRY_AUTO_INIT: "false"
  JAVA_TOOL_OPTIONS: "-javaagent:sentry-opentelemetry-agent.jar"
  OTEL_TRACES_EXPORTER: "none"
  OTEL_METRICS_EXPORTER: "none"
  OTEL_LOGS_EXPORTER: "none"
