# Staging secrets — fill in values before deploying
apiVersion: v1
kind: Secret
metadata:
    name: beanstash-secret
type: Opaque
stringData:
    SPRING_DATASOURCE_URL: ENC[AES256_GCM,data:gNlm/7nq3cfwUv5Ap3EwwYkIUEXcpxVnGVm/v5KvAxRjda4N47UnevjOc3cYsMULFNcA,iv:cYpcboifF9F+pH0neY5cUsTN8SDNEyX5URX88ZEIUdQ=,tag:7Ysi4josdW5XyQ14WCAZXQ==,type:str]
    SPRING_DATASOURCE_USERNAME: ENC[AES256_GCM,data:2tNcc5zbVBH1CcSxlw==,iv:lQMMoN8efi2k33McnwXqvw52TqGCjchxI3V+zDUotvs=,tag:g/97A80s3/S9oM2as1j8AA==,type:str]
    SPRING_DATASOURCE_PASSWORD: ENC[AES256_GCM,data:9KNOcqgzP258qhLeqQhNYp43ykXWEEdkFCvmI91Q,iv:Nbv9HVa1OeP9LeyLOcqeDHSN1D3fhkN7DuT1i5i10/8=,tag:Wx3ngZuFsccRlt8sqqyi5g==,type:str]
    SPRING_FLYWAY_USER: ENC[AES256_GCM,data:eMyudrxdXRCX,iv:nkOOn6PwWp+iVSB4EcG+9JdvsccLybwjDCEuxx+g+so=,tag:bNRmeZZbzByyOeEvJqGoFQ==,type:str]
    SPRING_FLYWAY_PASSWORD: ENC[AES256_GCM,data:/521VtYWCN+mD2XRmlTzeNQT/e51qlhbqiF/YcbW,iv:AanNcAS76tpOoe59W8WuSnUOXAK+2j9kQ+ZQuO5hCVI=,tag:4cEJFxIomV8dhyAoz4KIpg==,type:str]
    BASIC_AUTH_USER: ENC[AES256_GCM,data:o783j6gcppSE,iv:O2R+JQsUxPYySc5oLr+TYiNOe08I/Zdc1BGbK7wIaTo=,tag:9pfG3WqbXKJfr9JftvDYdQ==,type:str]
    BASIC_AUTH_PASSWORD: ENC[AES256_GCM,data:Jm8jU2WrbiumDQ==,iv:qyiX5pvaqfjI5CR9V4irXpxxTOiS/FHeyfa819uKnJE=,tag:E8046CJ3D3hLG8aI1oD09Q==,type:str]
    SENTRY_DSN: ENC[AES256_GCM,data:aD4Wnok/UZLGG/B9pq/jNqyJAzFoIKSwtW0Dje/qD3GfhP3jMUgiaJdus3oYKm5JP1XDTrI6Y69G+iTdvA==,iv:PokOMXqD1JVrOrJNGoz8rxK+NotDJnOb5AEZsYrszvQ=,tag:ZUoJkH2QzR3z5rNVvXyg3g==,type:str]
    NEXT_PUBLIC_SENTRY_DSN: ENC[AES256_GCM,data:BxYzckJibg1bnNQThTbbtwftFgBIUieXb23iDOxYbhN5rgD4EZ7qekTWgOK9g3mlBGga3cQ/F6XeYJITrg==,iv:hKZGaTUQCw01K/YZEE6QGv6Z/HI2WtU72ik541e7WTk=,tag:grc+gIBSO3Z2f8+WVYLi+w==,type:str]
sops:
    lastmodified: "2026-03-14T16:06:27Z"
    mac: ENC[AES256_GCM,data:I0Vo8sOFQc7gAWXSabLD2d2qH8aA8DV+Sf05iS9h57gWNPpNkA+EBCXiI3j5GJYINyWbLLambbTMG6Km5Iaf4q3jf4xcauIsEhgGgtz28lkxgbu5TrRKtufjxRkGzxW+4ZY3Jh6NwjiuQDXAYy3hwGUZg3Ic7zM3Ck6fwWbFw2s=,iv:HucQeeuL9TBZjmEfKizDYLOjGzcyXdHFvfABJ7YQ+/4=,tag:+6gB0WJ9RSvG/EtofwpUdA==,type:str]
    pgp:
        - created_at: "2026-03-14T16:06:27Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA/cF29oNCPyWAQ//XPHFy2btSSDNTPGxDGa/BoI4Mq4IJNCQX4z1fVToXHlA
            EFjLb24f9e4V+G0GwZdBe7ufNLEL9AEv1BhEujKqd8hfedW5senDgQy3q8D2KGix
            uwM1yug2zS566kL7SQpwCMRjaVVX3Qg8S5+QReFDKO5Dkuyis01u+fSwkyKwSGvs
            bipOrFQ7M619hPXmrWtoiQcNDt5PaF33Kx+ng9BrC08VCzjXLLcCLzfnc22dNucR
            s4aQqW8Cjs4IrLXy4aKoH2ZzaLlUDCds05TlmGH0yqbOa7VLy9Cece/4nWtV30pa
            qGLF/41lwlzyp/sjJINnmDvkHpM0CwXXtSd20y2G597zPXvDWCrU7nJADjbFmb4Z
            LvPHyQVW0y+DECkGbxc8SVRqOFRWFJLp/eXZHknFyfxE1BgUmIkbY6IJit4ZSEN4
            R27F4zsPFtS4VkOwCQH50XFo6rSdsZkSyOL6w5H4knJTjQJfQL+5FeFxvG1nL23c
            kG3szUPBDYFZu0kNR0iZeD3sDatTExnveGqslguM9teS3c6zwpTxgvNxIBhU54qr
            k57t5rhicj511tKSlOYjVb1aTR291kfK0euWWjQr912O0EjftLIvVCE5xIynWIgP
            jKOONMasJc41Tw/yjNhSQqxNENXQwCqXHu/D/j/IzjvYsD8d6VaxEVMxR0YM8hnU
            aAEJAhDemD+Q+1261z+0f6MSh7U9TsTMz9aY8gVgBMpZ7hL5rmWiUsi5dUExvkC3
            ha8+HTs9ab5r2w2y+iASIRnqz4B0uQHlFvMwaKgl0MIJz0ljHXTvTmGbZ9L+Fs7B
            eRE/EyPUU4xx
            =YJwP
            -----END PGP MESSAGE-----
          fp: 05F6A512DD349B0E33C7F417CBB5F307693F111D
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
---
apiVersion: v1
kind: Secret
metadata:
    name: beanstash-postgres-secret
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:E/VE/pkxWa9Q,iv:ZfvZkw/+nIJipmqfu/AiVsQPggGYhO1pwB24UUU1JUs=,tag:ClyBxPqDND+p9p1v5rSl5w==,type:str]
    password: ENC[AES256_GCM,data:l2Qwx44u3I+0pRqO+BZTC9MacUXfXdxm8BjWrKeu,iv:uZiZbZWIqbrLXMBykRc1YW+svLI1xMpxoiPFkDwVSXs=,tag:T37NKIcyVzYdzPp3fU8Byg==,type:str]
sops:
    lastmodified: "2026-03-14T16:06:27Z"
    mac: ENC[AES256_GCM,data:I0Vo8sOFQc7gAWXSabLD2d2qH8aA8DV+Sf05iS9h57gWNPpNkA+EBCXiI3j5GJYINyWbLLambbTMG6Km5Iaf4q3jf4xcauIsEhgGgtz28lkxgbu5TrRKtufjxRkGzxW+4ZY3Jh6NwjiuQDXAYy3hwGUZg3Ic7zM3Ck6fwWbFw2s=,iv:HucQeeuL9TBZjmEfKizDYLOjGzcyXdHFvfABJ7YQ+/4=,tag:+6gB0WJ9RSvG/EtofwpUdA==,type:str]
    pgp:
        - created_at: "2026-03-14T16:06:27Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA/cF29oNCPyWAQ//XPHFy2btSSDNTPGxDGa/BoI4Mq4IJNCQX4z1fVToXHlA
            EFjLb24f9e4V+G0GwZdBe7ufNLEL9AEv1BhEujKqd8hfedW5senDgQy3q8D2KGix
            uwM1yug2zS566kL7SQpwCMRjaVVX3Qg8S5+QReFDKO5Dkuyis01u+fSwkyKwSGvs
            bipOrFQ7M619hPXmrWtoiQcNDt5PaF33Kx+ng9BrC08VCzjXLLcCLzfnc22dNucR
            s4aQqW8Cjs4IrLXy4aKoH2ZzaLlUDCds05TlmGH0yqbOa7VLy9Cece/4nWtV30pa
            qGLF/41lwlzyp/sjJINnmDvkHpM0CwXXtSd20y2G597zPXvDWCrU7nJADjbFmb4Z
            LvPHyQVW0y+DECkGbxc8SVRqOFRWFJLp/eXZHknFyfxE1BgUmIkbY6IJit4ZSEN4
            R27F4zsPFtS4VkOwCQH50XFo6rSdsZkSyOL6w5H4knJTjQJfQL+5FeFxvG1nL23c
            kG3szUPBDYFZu0kNR0iZeD3sDatTExnveGqslguM9teS3c6zwpTxgvNxIBhU54qr
            k57t5rhicj511tKSlOYjVb1aTR291kfK0euWWjQr912O0EjftLIvVCE5xIynWIgP
            jKOONMasJc41Tw/yjNhSQqxNENXQwCqXHu/D/j/IzjvYsD8d6VaxEVMxR0YM8hnU
            aAEJAhDemD+Q+1261z+0f6MSh7U9TsTMz9aY8gVgBMpZ7hL5rmWiUsi5dUExvkC3
            ha8+HTs9ab5r2w2y+iASIRnqz4B0uQHlFvMwaKgl0MIJz0ljHXTvTmGbZ9L+Fs7B
            eRE/EyPUU4xx
            =YJwP
            -----END PGP MESSAGE-----
          fp: 05F6A512DD349B0E33C7F417CBB5F307693F111D
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
---
apiVersion: v1
kind: Secret
metadata:
    name: beanstash-staging-basic-auth
type: Opaque
# htpasswd format: user:$apr1$...
stringData:
    users: ENC[AES256_GCM,data:DYpHvtVwUxGUcLGAiHqgW0TjI2jVVydnhEs6b+mFLtUJvQSYhvO9/MS/I4kbsfo=,iv:5z8v1YfRQg9FhTW+k9hNe7j/gAOkNfKtfta+pIqSBLo=,tag:IgRNx8FyhDzAuzVfifJX/Q==,type:str]
sops:
    lastmodified: "2026-03-14T16:06:27Z"
    mac: ENC[AES256_GCM,data:I0Vo8sOFQc7gAWXSabLD2d2qH8aA8DV+Sf05iS9h57gWNPpNkA+EBCXiI3j5GJYINyWbLLambbTMG6Km5Iaf4q3jf4xcauIsEhgGgtz28lkxgbu5TrRKtufjxRkGzxW+4ZY3Jh6NwjiuQDXAYy3hwGUZg3Ic7zM3Ck6fwWbFw2s=,iv:HucQeeuL9TBZjmEfKizDYLOjGzcyXdHFvfABJ7YQ+/4=,tag:+6gB0WJ9RSvG/EtofwpUdA==,type:str]
    pgp:
        - created_at: "2026-03-14T16:06:27Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA/cF29oNCPyWAQ//XPHFy2btSSDNTPGxDGa/BoI4Mq4IJNCQX4z1fVToXHlA
            EFjLb24f9e4V+G0GwZdBe7ufNLEL9AEv1BhEujKqd8hfedW5senDgQy3q8D2KGix
            uwM1yug2zS566kL7SQpwCMRjaVVX3Qg8S5+QReFDKO5Dkuyis01u+fSwkyKwSGvs
            bipOrFQ7M619hPXmrWtoiQcNDt5PaF33Kx+ng9BrC08VCzjXLLcCLzfnc22dNucR
            s4aQqW8Cjs4IrLXy4aKoH2ZzaLlUDCds05TlmGH0yqbOa7VLy9Cece/4nWtV30pa
            qGLF/41lwlzyp/sjJINnmDvkHpM0CwXXtSd20y2G597zPXvDWCrU7nJADjbFmb4Z
            LvPHyQVW0y+DECkGbxc8SVRqOFRWFJLp/eXZHknFyfxE1BgUmIkbY6IJit4ZSEN4
            R27F4zsPFtS4VkOwCQH50XFo6rSdsZkSyOL6w5H4knJTjQJfQL+5FeFxvG1nL23c
            kG3szUPBDYFZu0kNR0iZeD3sDatTExnveGqslguM9teS3c6zwpTxgvNxIBhU54qr
            k57t5rhicj511tKSlOYjVb1aTR291kfK0euWWjQr912O0EjftLIvVCE5xIynWIgP
            jKOONMasJc41Tw/yjNhSQqxNENXQwCqXHu/D/j/IzjvYsD8d6VaxEVMxR0YM8hnU
            aAEJAhDemD+Q+1261z+0f6MSh7U9TsTMz9aY8gVgBMpZ7hL5rmWiUsi5dUExvkC3
            ha8+HTs9ab5r2w2y+iASIRnqz4B0uQHlFvMwaKgl0MIJz0ljHXTvTmGbZ9L+Fs7B
            eRE/EyPUU4xx
            =YJwP
            -----END PGP MESSAGE-----
          fp: 05F6A512DD349B0E33C7F417CBB5F307693F111D
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
